package com.example.calculator2


const val BUTTON_AC = "AC"
const val BUTTON_CHANGE = "+/-"
const val BUTTON_PERCENTAGE = "%"
const val BUTTON_DIVIDE = "/"
const val BUTTON_MULTIPLY = "*"
const val BUTTON_SUBTRACT = "-"
const val BUTTON_ADDITION = "+"
const val BUTTON_COMMA = "."
const val BUTTON_EQUAL = "="
const val NUMBER_0 = "0"
const val NUMBER_1 = "1"
const val NUMBER_2 = "2"
const val NUMBER_3 = "3"
const val NUMBER_4 = "4"
const val NUMBER_5 = "5"
const val NUMBER_6 = "6"
const val NUMBER_7 = "7"
const val NUMBER_8 = "8"
const val NUMBER_9 = "9"